########################################
# XDG BASE LAYER (DO NOT CHANGE OFTEN)
########################################

XDG_CONFIG_HOME=/home/vash/.config
XDG_DATA_HOME=/home/vash/.local/share
XDG_CACHE_HOME=/home/vash/.cache
XDG_STATE_HOME=/home/vash/.local/state

########################################
# SYSTEM IDENTITY
########################################

LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8

########################################
# SESSION CORE
########################################

DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
