# ---- Core system ----
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8

# ---- Desktop ----
KDE_FULL_SESSION=true
KDE_SESSION_VERSION=6

# ---- GUI apps ----
EDITOR=nvim
VISUAL=nvim
BROWSER=google-chrome-stable
TERMINAL=konsole

# ---- Java ----
JAVA_HOME=/usr/lib/jvm/default
_JAVA_AWT_WM_NONREPARENTING=1
